//JSON: Javascript Object Notation
var IMAGE_SERVER_PATH = "images/";
var IMAGE_LINK_PATH = "../raoheShops/";
var SHOP_LINK_PATH = "parent.location='../raoheShops/";
var marketData = [
					
					{
						"title": "Raohe Night Market",
						"lat": 25.050365,
				 		"lng": 121.573173,
						"distance": 1.2,
						"markerImg": "1.png" ,
						"markerLink":"",
						"tagline": "The first Taipei night market",
						"marketIcon": "marketIcon_raohe.png"	
						
					},
					{
						"title": "Tonghau Night Market",
						"lat": 25.031126,
				 		"lng": 121.55429,
						"distance": 2,
						"markerImg": "1.png" ,
						"marketImg": "1.png" ,
						"tagline": "Asitable market for visitors on a tight schedule",
						"marketIcon": "marketIcon_tonghua.png"		
						
					},
					{
						"title": "Hauxi Night Market",
						"lat": 25.035623,
				 		"lng": 121.498401,
						"distance": 6,
						"markerImg": "1.png" ,
						"marketImg": "1.png" ,
						"tagline": "Tourists' favorite market",
						"marketIcon": "marketIcon_hauxi.png"	
						
					},
					{
						"title": "Shilin Night Market",
						"lat": 25.088027,
				 		"lng": 121.526126,
						"distance": 5.2,
						"markerImg": "1.png" ,
						"marketImg": "1.png" ,
						"tagline": "The biggest Taipei night market",
						"marketIcon": "marketIcon_shilin.png"	
						
					},
					{
						"title": "NingXia Night Market",
						"lat": 25.056228,
				 		"lng": 121.515350,
						"distance": 4.6,
						"markerImg": "1.png" ,
						"marketImg": "1.png" ,
						"tagline": "The smallest Taipei night market",
						"marketIcon": "marketIcon_ningxia.png"	
						
					},
					{
						"title": "You are here!",
						"lat": 25.059265, 
				 		"lng": 121.543550,
						"distance": 0,
						"markerImg": "1.png" ,
						"marketImg": "1.png" ,
						"tagline": "",
						"marketIcon": "youAreHere.png"	
						
					}
					
					
					
				 ]

var raoheShops = [
				 {"check":"true", 
				  "lat": 25.050301,
				  "lng": 121.572866,
				  "category":"dinner",
				  "icon":"open.png",
				  "price":"m",
				  "rating":"4",
				  "title": "Liau Restaurant",
				  "distance": "0.2 mile",
				  "description": "Chinese Cuisine",
				  "cashCredit": "Cash Only",
				  "shopImg": "liauRestaurant.png",
				  "imglink": "",
				  "foodCategoryImg": "foodCategory.png",
				  "openCloseImg": "open.png",
				  "priceImg": "price.png",
				  "ratingImg": "rating_5.png",
				  "favorite": "",
				  "getDirectionImg": "btn_getDirections.png",
				  "filterIcon": "filterIcons_dinner.png",
				  "listLink": "images/liau_list.jpg"
				  
				},
				{ "check":"true",
				  "lat": 25.050486,
				  "lng": 121.574035,
				  "category":"vegetarian",
				  "price":"l",
				  "rating":"4",
				  "title": "Stinking Tofu",
				  "distance": "0.1 mile",
				  "description": "Fried Tofu",
				  "cashCredit": "Cash Only",
				  "shopImg": "stinkingTofu.png",
				  "imglink": "",
				  "foodCategoryImg": "foodCategory.png",
				  "openCloseImg": "open.png",
				  "priceImg": "price.png",
				  "ratingImg": "rating_4.png",
				  "favorite": "favorite",
				  "getDirectionImg": "btn_getDirections.png",
				  "filterIcon": "filterIcons_vegetarian.png",
				  "listLink": "images/stinking_list.jpg"
				},
				{ "check":"true",
				  "lat": 25.050272,
				  "lng": 121.573316,
				  "category":"dinner",
				  "price":"h",
				  "rating":"5",
				  "title": "Wang Beef Noodles",
				  "distance": "0.2 mile",
				  "description": "Beef Noodles",
				  "cashCredit": "Cash Only",
				  "shopImg": "wangBeef.png",
				  "imglink": "",
				  "foodCategoryImg": "foodCategory.png",
				  "openCloseImg": "open.png",
				  "priceImg": "price.png",
				  "ratingImg": "rating_5.png",
				  "favorite": "favorite",
				  "getDirectionImg": "btn_getDirections.png",
				  "filterIcon": "filterIcons_dinner.png",
				  "listLink": "images/wangBeef_list.jpg"
				},
				{ "check":"true",
				  "lat": 25.05035,
				  "lng": 121.574596,
				  "category":"dinner",
				  "price":"m",
				  "rating":"4",
				  "title": "Tappasaki",
				  "distance": "0.2 mile",
				  "description": "steak meal",
				  "cashCredit": "Cash Only",
				  "shopImg": "tappasaki.png",
				  "imglink": "",
				  "foodCategoryImg": "foodCategory.png",
				  "openCloseImg": "open.png",
				  "priceImg": "price.png",
				  "ratingImg": "rating_4.png",
				  "favorite": "",
				  "getDirectionImg": "btn_getDirections.png",
				  "filterIcon": "filterIcons_dinner.png",
				  "listLink": "images/tappasaki_list.jpg"
				},
			  	
				{ "check":"true", 
				  "lat": 25.050059,
				  "lng": 121.572797,
				  "category":"drinks",
				  "price":"l",
				  "rating":"5",
				  "title": "Tea Shop",
				  "distance": "0.2 mile",
				  "description": "Soft Drinks",
				  "cashCredit": "Cash Only",
				  "shopImg": "teashop.png",
				  "imglink": "teaShop.html",
				  "foodCategoryImg": "foodCategory.png",
				  "openCloseImg": "open.png",
				  "priceImg": "price.png",
				  "ratingImg": "rating_5.png",
				  "favorite": "favorite",
				  "getDirectionImg": "btn_getDirections.png",
				  "filterIcon": "filterIcons_drinks.png",
				  "listLink": "images/teaShop_list.jpg"
				},
				{ "check":"true",
				  "lat": 25.050341,
				  "lng": 121.574557,
				  "category":"drinks",
				  "price":"l",
				  "rating":"4",
				  "title": "Ice Tea",
				  "distance": "0.2 mile",
				  "description": "Icy Drinks",
				  "cashCredit": "Cash Only",
				  "shopImg": "iceTea.png",
				  "imglink": "",
				  "foodCategoryImg": "foodCategory.png",
				  "openCloseImg": "open.png",
				  "priceImg": "price.png",
				  "ratingImg": "rating_4.png",
				  "favorite": "favorite",
				  "getDirectionImg": "btn_getDirections.png",
				  "filterIcon": "filterIcons_drinks.png",
				  "listLink": "images/iceTea_list.jpg"
				},
				{ "check":"true",
				  "lat": 25.050469,
				  "lng": 121.57416,
				  "category":"vegetarian",
				  "price":"l",
				  "rating":"5",
				  "title": "Juice Shop",
				  "distance": "0.2 mile",
				  "description": "Fruit and vegetable juice",
				  "cashCredit": "Cash Only",
				  "shopImg": "juiceShop.png",
				  "imglink": "juiceShop.html",
				  "foodCategoryImg": "foodCategory.png",
				  "openCloseImg": "open.png",
				  "priceImg": "price.png",
				  "ratingImg": "rating_5.png",
				  "favorite": "",
				  "getDirectionImg": "btn_getDirections.png",
				  "filterIcon": "filterIcons_vegetarian.png",
				  "listLink": "images/juiceShop_list.jpg"
				},
				{ "check":"true",
				  "lat": 25.050214,
				  "lng": 121.572691,
				  "category":"icyFoods",
				  "price":"l",
				  "rating":"4",
				  "title": "Shaved Ice",
				  "distance": "0.2 mile",
				  "description": "Fresh fruit chaved ice",
				  "cashCredit": "Cash Only",
				  "shopImg": "shavedIce.png",
				  "imglink": "",
				  "foodCategoryImg": "foodCategory.png",
				  "openCloseImg": "open.png",
				  "priceImg": "price.png",
				  "ratingImg": "rating_5.png",
				  "favorite": "favorite",
				  "getDirectionImg": "btn_getDirections.png",
				  "filterIcon": "filterIcons_icyFoods.png",
				  "listLink": "images/shavedIce_list.jpg"
				},
			  	
				{ "check":"true",
				  "lat": 25.050443,
				  "lng": 121.57387,
				  "category":"fingerFoods",
				  "price":"l",
				  "rating":"5",
				  "title": "HauDa Fried Chicken",
			      "distance": "0.2 mile",
		    	  "description": "Fried Chicken Steak",
			      "cashCredit": "Cash Only",
	    	      "shopImg": "hauda.png",
				  "imglink": "",
			      "foodCategoryImg": "foodCategory.png",
			      "openCloseImg": "open.png",
			      "priceImg": "price.png",
			      "ratingImg": "rating_5.png",
				  "favorite": "",
				  "getDirectionImg": "btn_getDirections.png",
				  "filterIcon": "filterIcons_fingerFoods.png",
				  "listLink": "images/hauda_list.jpg"
			     },
			     { "check":"true",
				   "lat": 25.050365,
				   "lng": 121.573173,
				   "category":"fingerFoods",
				   "price":"l",
				   "rating":"4",
				   "title": "Pancake",
				   "distance": "0.2 mile",
				   "description": "Pancake",
				   "cashCredit": "Cash Only",
				   "shopImg": "pancake.png",
				   "imglink": "",
				   "foodCategoryImg": "foodCategory.png",
				   "openCloseImg": "open.png",
				   "priceImg": "price.png",
				   "ratingImg": "rating_4.png",
				  "favorite": "favorite",
				  "getDirectionImg": "btn_getDirections.png",
				  "filterIcon": "filterIcons_fingerFoods.png",
				  "listLink": "images/pancake_list.jpg"
				 }
			     ]


