//JSON: Javascript Object Notation
var IMAGE_SERVER_PATH = "images/";

var marketData = [
					{
						"title": "Raohe Night Market",
						"lat": 25.050365,
				 		"lng": 121.573173,
						"distance": 1.2,
						"markerImg": "1.png" ,
						"marketImg": "1.png" ,
						"tagline": "The first Taipei night market"	
						
					},
					{
						"title": "Tonghau Night Market",
						"lat": 25.031126,
				 		"lng": 121.55429,
						"distance": 2,
						"markerImg": "1.png" ,
						"marketImg": "1.png" ,
						"tagline": "Asitable market for visitors on a tight schedule"	
						
					},
					{
						"title": "Hauxi Night Market",
						"lat": 25.035623,
				 		"lng": 121.498401,
						"distance": 6,
						"markerImg": "1.png" ,
						"marketImg": "1.png" ,
						"tagline": "Tourists' favorite market"	
						
					},
					{
						"title": "Shilin Night Market",
						"lat": 25.088027,
				 		"lng": 121.526126,
						"distance": 5.2,
						"markerImg": "1.png" ,
						"marketImg": "1.png" ,
						"tagline": "The biggest Taipei night market"	
						
					},
					{
						"title": "NingXia Night Market",
						"lat": 25.056228,
				 		"lng": 121.515350,
						"distance": 4.6,
						"markerImg": "1.png" ,
						"marketImg": "1.png" ,
						"tagline": "The smallest Taipei night market"	
						
					}
					
					
					
				 ]

var raoheShops = [
				 {"check":"true", 
				  "lat": 25.050365,
				  "lng": 121.573173,
				  "category":"dinner",
				  "icon":"open.png",
				  "price":"l",
				  "rating":"4",
				  "title": "Liau Restaurant",
				  "distance": "1.2 mile",
				  "description": "Chinese Cuisine",
				  "cashCredit": "Cash Only",
				  "shopImg": "shopImg.png",
				  "foodCategoryImg": "foodCategory.png",
				  "openCloseImg": "open.png",
				  "priceImg": "price.png",
				  "ratingImg": "rating_5.png",
				  "favorite": "favorite"
				  
				},
				{ "check":"true",
				  "lat": 25.050214,
				  "lng": 121.572691,
				  "category":"dinner",
				  "price":"l",
				  "rating":"4",
				  "title": "Stinking Tofu",
				  "distance": "1.2 mile",
				  "description": "Fried Tofu",
				  "cashCredit": "Cash Only",
				  "shopImg": "shopImg.png",
				  "foodCategoryImg": "foodCategory.png",
				  "openCloseImg": "open.png",
				  "priceImg": "price.png",
				  "ratingImg": "rating_4.png",
				  "favorite": ""
				},
				{ "check":"true",
				  "lat": 25.050272,
				  "lng": 121.573316,
				  "category":"dinner",
				  "price":"m",
				  "rating":"5",
				  "title": "Wang Beef Noodles",
				  "distance": "1.2 mile",
				  "description": "Beef Noodles",
				  "cashCredit": "Cash Only",
				  "shopImg": "shopImg.png",
				  "foodCategoryImg": "foodCategory.png",
				  "openCloseImg": "open.png",
				  "priceImg": "price.png",
				  "ratingImg": "rating_5.png",
				  "favorite": "favorite"
				},
				{ "check":"true",
				  "lat": 25.05035,
				  "lng": 121.574596,
				  "category":"dinner",
				  "price":"l",
				  "rating":"4",
				  "title": "Tappasaki",
				  "distance": "1.2 mile",
				  "description": "Seafood",
				  "cashCredit": "Cash Only",
				  "shopImg": "shopImg.png",
				  "foodCategoryImg": "foodCategory.png",
				  "openCloseImg": "open.png",
				  "priceImg": "price.png",
				  "ratingImg": "rating_4.png",
				  "favorite": ""
				},
			  	
				{ "check":"true", 
				  "lat": 25.050059,
				  "lng": 121.572797,
				  "category":"drinks",
				  "price":"l",
				  "rating":"4",
				  "title": "Tea Shop",
				  "distance": "1.2 mile",
				  "description": "Soft Drinks",
				  "cashCredit": "Cash Only",
				  "shopImg": "shopImg.png",
				  "foodCategoryImg": "foodCategory.png",
				  "openCloseImg": "open.png",
				  "priceImg": "price.png",
				  "ratingImg": "rating_5.png",
				  "favorite": "favorite"
				},
				{ "check":"true",
				  "lat": 25.050341,
				  "lng": 121.574557,
				  "category":"drinks",
				  "price":"l",
				  "rating":"4",
				  "title": "Bubble Mike Tea",
				  "distance": "1.2 mile",
				  "description": "Tapioca Drinks",
				  "cashCredit": "Cash Only",
				  "shopImg": "shopImg.png",
				  "foodCategoryImg": "foodCategory.png",
				  "openCloseImg": "open.png",
				  "priceImg": "price.png",
				  "ratingImg": "rating_4.png",
				  "favorite": ""
				},
				{ "check":"true",
				  "lat": 25.050301,
				  "lng": 121.572866,
				  "category":"vegetarian",
				  "price":"l",
				  "rating":"4",
				  "title": "Tapioca",
				  "distance": "1.2 mile",
				  "description": "Soft Drinks",
				  "cashCredit": "Cash Only",
				  "shopImg": "shopImg.png",
				  "foodCategoryImg": "foodCategory.png",
				  "openCloseImg": "open.png",
				  "priceImg": "price.png",
				  "ratingImg": "rating_5.png",
				  "favorite": ""
				},
				{ "check":"true",
				  "lat": 25.050486,
				  "lng": 121.574035,
				  "category":"icyFoods",
				  "price":"l",
				  "rating":"4",
				  "title": "Bill shaved Ice",
				  "distance": "1.2 mile",
				  "description": "Fresh Fruit Juice",
				  "cashCredit": "Cash Only",
				  "shopImg": "shopImg.png",
				  "foodCategoryImg": "foodCategory.png",
				  "openCloseImg": "open.png",
				  "priceImg": "price.png",
				  "ratingImg": "rating_5.png",
				  "favorite": "favorite"
				},
			  	
				{ "check":"true",
				  "lat": 25.050443,
				  "lng": 121.57387,
				  "category":"fingerFoods",
				  "price":"l",
				  "rating":"4",
				  "title": "Hau Da Fried Chicken",
			      "distance": "1.2 mile",
		    	  "description": "Fried Chicken Steak",
			      "cashCredit": "Cash Only",
	    	      "shopImg": "shopImg.png",
			      "foodCategoryImg": "foodCategory.png",
			      "openCloseImg": "open.png",
			      "priceImg": "price.png",
			      "ratingImg": "rating_5.png",
				  "favorite": ""
			     },
			     { "check":"true",
				   "lat": 25.050469,
				   "lng": 121.57416,
				   "category":"fingerFoods",
				   "price":"l",
				   "rating":"5",
				   "title": "Pancake",
				   "distance": "1.2 mile",
				   "description": "Pancake",
				   "cashCredit": "Cash Only",
				   "shopImg": "shopImg.png",
				   "foodCategoryImg": "foodCategory.png",
				   "openCloseImg": "open.png",
				   "priceImg": "price.png",
				   "ratingImg": "rating_4.png",
				  "favorite": "favorite"
				 }
			     ]


