//JSON: Javascript Object Notation
var IMAGE_SERVER_PATH = "images/";
var raoheShops = {
	"dinner": [ { "lat": 25.050365,
				  "lng": 121.573173,
				  "category":"dinner",
				  "Price":"$",
				  "Rating":"4",
				  "title": "Liau Restaurant",
				  "distance": "1.2 mile",
				  "description": "Chinese Cuisine",
				  "cashCredit": "Cash Only",
				  "shopImg": "shopImg.png",
				  "foodCategoryImg": "foodCategory.png",
				  "openCloseImg": "open.png",
				  "priceImg": "price.png",
				  "ratingImg": "rating_5.png"
				},
				{ "lat": 25.050214,
				  "lng": 121.572691,
				  "category":"dinner",
				  "Price":"$",
				  "Rating":"4",
				  "title": "Stinking Tofu",
				  "distance": "1.2 mile",
				  "description": "Fried Tofu",
				  "cashCredit": "Cash Only",
				  "shopImg": "shopImg.png",
				  "foodCategoryImg": "foodCategory.png",
				  "openCloseImg": "open.png",
				  "priceImg": "price.png",
				  "ratingImg": "rating_4.png"
				},
				{ "lat": 25.050272,
				  "lng": 121.573316,
				  "category":"dinner",
				  "Price":"$$",
				  "Rating":"5",
				  "title": "Wang Beef Noodles",
				  "distance": "1.2 mile",
				  "description": "Beef Noodles",
				  "cashCredit": "Cash Only",
				  "shopImg": "shopImg.png",
				  "foodCategoryImg": "foodCategory.png",
				  "openCloseImg": "open.png",
				  "priceImg": "price.png",
				  "ratingImg": "rating_5.png"
				},
				{ "lat": 25.05035,
				  "lng": 121.574596,
				  "category":"dinner",
				  "Price":"$",
				  "Rating":"4",
				  "title": "Tappasaki",
				  "distance": "1.2 mile",
				  "description": "Seafood",
				  "cashCredit": "Cash Only",
				  "shopImg": "shopImg.png",
				  "foodCategoryImg": "foodCategory.png",
				  "openCloseImg": "open.png",
				  "priceImg": "price.png",
				  "ratingImg": "rating_4.png"
				}
			  ],	
	"drinks": [	{ "lat": 25.050059,
				  "lng": 121.572797,
				  "category":"drinks",
				  "Price":"$",
				  "Rating":"4",
				  "title": "Tea Shop",
				  "distance": "1.2 mile",
				  "description": "Soft Drinks",
				  "cashCredit": "Cash Only",
				  "shopImg": "shopImg.png",
				  "foodCategoryImg": "foodCategory.png",
				  "openCloseImg": "open.png",
				  "priceImg": "price.png",
				  "ratingImg": "rating_5.png"
				},
				{ "lat": 25.050341,
				  "lng": 121.574557,
				  "category":"drinks",
				  "Price":"$",
				  "Rating":"4",
				  "title": "Bubble Mike Tea",
				  "distance": "1.2 mile",
				  "description": "Tapioca Drinks",
				  "cashCredit": "Cash Only",
				  "shopImg": "shopImg.png",
				  "foodCategoryImg": "foodCategory.png",
				  "openCloseImg": "open.png",
				  "priceImg": "price.png",
				  "ratingImg": "rating_4.png"
				},
				{ "lat": 25.050301,
				  "lng": 121.572866,
				  "category":"drinks",
				  "Price":"$",
				  "Rating":"4",
				  "title": "Tapioca",
				  "distance": "1.2 mile",
				  "description": "Soft Drinks",
				  "cashCredit": "Cash Only",
				  "shopImg": "shopImg.png",
				  "foodCategoryImg": "foodCategory.png",
				  "openCloseImg": "open.png",
				  "priceImg": "price.png",
				  "ratingImg": "rating_5.png"
				},
				{ "lat": 25.050486,
				  "lng": 121.574035,
				  "category":"drinks",
				  "Price":"$",
				  "Rating":"4",
				  "title": "Bill Juice",
				  "distance": "1.2 mile",
				  "description": "Fresh Fruit Juice",
				  "cashCredit": "Cash Only",
				  "shopImg": "shopImg.png",
				  "foodCategoryImg": "foodCategory.png",
				  "openCloseImg": "open.png",
				  "priceImg": "price.png",
				  "ratingImg": "rating_5.png"
				}
			  ],	
	"fingerfoods": [ { "lat": 25.050443,
				       "lng": 121.57387,
				 	   "category":"fingerfoods",
					   "Price":"$",
					   "Rating":"4",
				 	   "title": "Hau Da Fried Chicken",
				  	   "distance": "1.2 mile",
				  	   "description": "Fried Chicken Steak",
				       "cashCredit": "Cash Only",
				       "shopImg": "shopImg.png",
				       "foodCategoryImg": "foodCategory.png",
				       "openCloseImg": "open.png",
				       "priceImg": "price.png",
				       "ratingImg": "rating_5.png"
				     },
				     { "lat": 25.050469,
				       "lng": 121.57416,
					   "category":"fingerfoods",
					   "Price":"$",
					   "Rating":"5",
				       "title": "Pancake",
				       "distance": "1.2 mile",
				       "description": "Pancake",
				       "cashCredit": "Cash Only",
				       "shopImg": "shopImg.png",
				       "foodCategoryImg": "foodCategory.png",
				       "openCloseImg": "open.png",
				       "priceImg": "price.png",
				       "ratingImg": "rating_4.png"
				     }
			       ]
}

